konstructio/konstruct-ui

lib/components/Radio/Radio.stories.tsx
lib/components/Radio/Radio.test.tsx
lib/components/Radio/Radio.tsx
lib/components/Radio/Radio.types.ts
lib/components/Radio/Radio.variants.ts
lib/components/RadioGroup/RadioGroup.stories.tsx
lib/components/RadioGroup/RadioGroup.test.tsx
lib/components/RadioGroup/RadioGroup.tsx
lib/components/RadioGroup/RadioGroup.types.ts
lib/components/RadioGroup/RadioGroup.variants.ts

✨ feat: enhance radio component 

---

.github/workflows/deploy-storybook.yml
.github/workflows/release-package.yml
.github/workflows/tests.yml
.github/workflows/update-changelog.yml

Update workflow to utilize workflows.
We are running out of GitHub Action usage.

chore: use selfhosted runner for workflows

---

lib/components/Alert/Alert.stories.tsx
lib/components/Alert/Alert.test.tsx
lib/components/Alert/Alert.tsx
lib/components/Alert/Alert.types.ts
lib/components/Alert/Alert.variants.ts
lib/components/index.ts
lib/plugins/konstruct.ts
lib/plugins/utils/animation.styles.ts
lib/plugins/utils/index.ts

✨ feat: the Alert component was added

---

.gitignore
lib/assets/icons/circle.svg
lib/components/Divider/Divider.stories.tsx
lib/components/Divider/Divider.tsx
lib/components/Divider/Divider.variants.ts
lib/components/Loading/Loading.stories.tsx
lib/components/Loading/Loading.tsx
lib/components/Loading/Loading.types.ts
lib/components/Loading/Loading.variants.ts
lib/components/Typography/Typography.stories.tsx
lib/components/Typography/Typography.tsx
lib/components/Typography/Typography.types.ts
lib/components/Typography/Typography.variants.ts
lib/components/index.ts
package.json

- Adds Typography, loading and divider

feat: adding typography, loading and divider

---

lib/components/Modal/Modal.stories.tsx
lib/components/Modal/Modal.test.tsx
lib/components/Modal/Modal.tsx
lib/components/Modal/Modal.types.ts
lib/components/Modal/components/Wrapper/Wrapper.tsx
lib/components/Modal/components/Wrapper/Wrapper.types.ts

- fix: control modal from props instead of provider

fix: modal, remove unnecessary provider

---

.github/workflows/release-package.yml
.github/workflows/update-changelog.yml

This PR updates KBOT_TOKEN variable to the standard GH_TOKEN we use across all our repositories. 
Fixes #
https://github.com/konstructio/gitops/pull/398

feat: change KBOT_TOKEN to GH_TOKEN

---

lib/components/Autocomplete/Autocomplete.variants.ts
lib/components/Input/Input.tsx
lib/components/Input/Input.types.ts
lib/components/Input/Input.variants.ts
lib/components/TextArea/TextArea.tsx
lib/components/TextArea/TextArea.types.ts
lib/components/TextArea/TextArea.variants.ts

fix: class names

---

lib/components/Input/Input.tsx
lib/components/Input/Input.variants.ts
lib/components/Typography/Typography.variants.ts

fix: error states and default styles

fix: error states

---

lib/components/Toast/Toast.variants.ts

fix: remove default background for toast

fix: remove toast background

---

lib/components/Dropdown/Dropdown.stories.tsx
lib/components/Dropdown/Dropdown.types.ts
lib/components/Dropdown/Dropdown.variants.ts
lib/components/Dropdown/components/List/List.variants.ts
lib/components/Dropdown/components/ListItem/ListItem.tsx
lib/components/Dropdown/components/Wrapper.tsx

fix: dropdown styles

---

lib/components/Dropdown/Dropdown.stories.tsx
lib/components/Dropdown/Dropdown.test.tsx
lib/components/Dropdown/Dropdown.tsx
lib/components/Dropdown/Dropdown.types.ts
lib/components/Dropdown/components/Wrapper.tsx
lib/components/Dropdown/contexts/dropdown.context.tsx
lib/components/Dropdown/contexts/dropdown.provider.tsx
lib/components/Sidebar/components/Logo/Logo.variants.ts

fix: dropdown state

---

lib/components/Dropdown/Dropdown.test.tsx
lib/components/Dropdown/Dropdown.types.ts
lib/components/Dropdown/contexts/dropdown.provider.tsx

fix: dropdown types

---

lib/components/Table/Table.stories.tsx
lib/components/Table/components/Filter.tsx
lib/components/index.ts

feat: filter child

---

lib/components/Dropdown/Dropdown.stories.tsx
lib/components/Dropdown/Dropdown.types.ts
lib/components/Dropdown/components/Wrapper.tsx
lib/components/Switch/Switch.variants.ts

- Adds loading state for dropdown
- Fix switch to match designs

feat: loading state for dropdown and switch fix to match designs

---

lib/components/Dropdown/Dropdown.stories.tsx
lib/components/Dropdown/Dropdown.test.tsx
lib/components/Dropdown/Dropdown.tsx
lib/components/Dropdown/Dropdown.types.ts
lib/components/Dropdown/components/ListItem/ListItem.tsx
lib/components/Dropdown/components/Wrapper.tsx
lib/components/Dropdown/contexts/dropdown.context.tsx
lib/components/Dropdown/contexts/dropdown.provider.tsx

fix: use internal state for option dropdown

fix: dropdown state text

---

lib/components/NumberInput/NumberInput.stories.tsx
lib/components/NumberInput/NumberInput.test.tsx
lib/components/NumberInput/NumberInput.tsx
lib/components/NumberInput/NumberInput.types.ts
lib/components/NumberInput/NumberInput.variants.ts

- fixes number input design and stateless

fix: number input design

---

lib/components/Dropdown/Dropdown.test.tsx
lib/components/Dropdown/components/List/List.tsx
lib/components/Dropdown/components/List/List.types.ts
lib/components/Dropdown/components/ListItem/ListItem.tsx
lib/components/Dropdown/components/ListItem/ListItem.types.ts
lib/components/Dropdown/components/Wrapper.tsx

- Adds loading state and empty states for dropdown

feat: loading and empty states for dropdown

---

lib/components/Table/Table.variants.ts
lib/index.css

fix: table shadow

---

lib/components/Divider/Divider.variants.ts

fix: divider

---

lib/components/Tabs/Tabs.stories.tsx
lib/components/Tabs/Tabs.test.tsx
lib/components/Tabs/Tabs.tsx
lib/components/Tabs/Tabs.types.ts
lib/components/Tabs/Tabs.variants.ts
lib/components/Tabs/components/Content.tsx
lib/components/Tabs/components/List.tsx
lib/components/Tabs/components/Trigger.tsx
package-lock.json
package.json

- Adds tabs component with horizontal and vertical variants

feat: tabs component

---

.github/workflows/update-changelog.yml

fix: ruby setup workflow

---

lib/components/Button/Button.types.ts
lib/components/DropdownButton/DropdownButton.stories.tsx
lib/components/DropdownButton/DropdownButton.tsx
lib/components/DropdownButton/DropdownButton.types.ts

✨ feat: dropdown button was added

---

lib/components/Radio/Radio.tsx
lib/components/Radio/Radio.types.ts
lib/components/RadioCard/RadioCard.tsx
lib/components/RadioCard/RadioCard.types.ts
lib/components/RadioCardGroup/RadioCardGroup.stories.tsx
lib/components/RadioCardGroup/RadioCardGroup.test.tsx
lib/components/RadioCardGroup/RadioCardGroup.tsx

Adding radio group description

feat: added radio card description

---

lib/components/Input/Input.tsx

fix: show password

---

lib/components/Modal/Modal.tsx
lib/components/Modal/Modal.types.ts

- feat: add optional container to modal

feat: add optional container to modal

---

lib/components/Button/Button.stories.tsx
lib/components/Button/Button.variants.ts

feat: civo dark button

---

lib/components/Toast/Toast.variants.ts

- Removing borders and shadow for toast dark mode

fix: dark styles for toast
